"""
Django settings for djangoproj project.

Generated by 'django-admin startproject' using Django 3.2.5.
"""

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    # Admin interface
    path("admin/", admin.site.urls),

    # Django app API endpoints
    path("djangoapp/", include("djangoapp.urls")),

    # Serve React frontend (SPA) for all non-API routes
    path("", TemplateView.as_view(template_name="index.html")),
    path("about/", TemplateView.as_view(template_name="index.html")),
    path("contact/", TemplateView.as_view(template_name="index.html")),
    path("login/", TemplateView.as_view(template_name="index.html")),
    path("register/", TemplateView.as_view(template_name="index.html")),
    path("dealers/", TemplateView.as_view(template_name="index.html")),
    path(
        "dealer/<int:dealer_id>/",
        TemplateView.as_view(template_name="index.html"),
    ),
    path(
        "postreview/<int:dealer_id>/",
        TemplateView.as_view(template_name="index.html"),
    ),

    # Catch-all route for React Router (important!)
    path("<path:path>", TemplateView.as_view(template_name="index.html")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
